---
jaffle_shop:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: localhost
      user: postgres
      pass: postgres
      port: 5432
      schema: dbt_unit_testing_jaffle_shop
      dbname: postgres
      threads: 1

    bq:
      dataset: dbt_flow_wfuks
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/will/.dbt/carrefour-bq-dbt.json
      location: US
      method: service-account
      priority: interactive
      project: carrefour-370314
      threads: 1
      type: bigquery

