---
version: 2

metrics:
  - name: average_order_amount
    label: Average Order Amount
    model: ref('customers')
    description: "The average size of a jaffle order"
    calculation_method: average
    expression: customer_lifetime_value
    timestamp: most_recent_order
    time_grains: [day, all_time]

  - name: total_order_amount
    label: Total Order Amount
    model: ref('customers')
    description: "The average size of a jaffle order"
    calculation_method: sum
    expression: customer_lifetime_value
    timestamp: most_recent_order
    time_grains: [day, all_time]

  - name: derived_test
    label: der_test
    calculation_method: derived
    expression: "{{metric('average_order_amount')}} / {{metric('total_order_amount')}}"
    timestamp: most_recent_order
    time_grains: [day, all_time]

models:
  - name: customers
    description: >-
      This table has basic information about a customer, as well
      as some derived facts based on a customer's orders
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer's first name. PII.
      - name: last_name
        description: Customer's last name. PII.
      - name: first_order
        description: Date (UTC) of a customer's first order
      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order
      - name: number_of_orders
        description: Count of the number of orders a customer has placed
      - name: customer_lifetime_value
        description: CLTV of a customer's purchases

