---
name: 'dbt_flow'
version: '0.0.1'
config-version: 2

require-dbt-version: [">=1.3.0"]

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"
