---
name: "dbt_flow_integration_tests"
version: "0.0.1"
config-version: 2

profile: "integration_tests"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "dbt_packages"

vars:
  flow_config:
    verbose: false
