---
version: 2

sources:
  - name: test_source_customers
    database: test_database
    schema: test_schema
    tables:
      - name: test_customers
        identifier: test_customers_identifier

models:
  - name: stg__customers
    columns:
      - name: customer_id
      - name: first_name
      - name: last_name

  - name: stg__orders
    columns:
      - name: order_id
      - name: customer_id
      - name: order_date
      - name: status

  - name: stg__payments
    columns:
      - name: payment_id
      - name: order_id
      - name: payment_method
      - name: amount
