version: 2

sources:
  - name: dbt_unit_testing
    tables:
      - name: sample_source
        columns:
          - name: source_a
            data_type: integer
          - name: source_b
      - name: sample_source_without_columns_declared
      - name: source-with-dashes
        columns:
          - name: example
            data_type: integer
        quoting:
          identifier: true
      - name: sample_source_name
        identifier: sample_source_identifier

  - name: source_from_schema_1
    schema: dbt_unit_testing_schema_1
    tables:
      - name: multi_schema
        identifier: multi_schema
        columns:
          - name: name

  - name: source_from_schema_2
    schema: dbt_unit_testing_schema_2
    tables:
      - name: multi_schema
        identifier: multi_schema
        columns:
          - name: name
